# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{residence}
  s.version = "0.0.18"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andy Rossmeissl", "Seamus Abshere", "Ian Hough", "Matt Kling", "Derek Kastner"]
  s.date = %q{2010-12-16}
  s.description = %q{A software model in Ruby for the greenhouse gas emissions of an residence}
  s.email = %q{andy@rossmeissl.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "lib/residence.rb",
     "lib/residence/carbon_model.rb",
     "lib/residence/characterization.rb",
     "lib/residence/data.rb",
     "lib/residence/fallback.rb",
     "lib/residence/relationships.rb",
     "lib/residence/summarization.rb",
     "lib/test_support/residence_record.rb"
  ]
  s.homepage = %q{http://github.com/brighterplanet/residence}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A carbon model}
  s.test_files = [
    "features/support/env.rb",
     "features/residence_emissions.feature",
     "features/residence_committees.feature",
     "lib/test_support/residence_record.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<sniff>, [">= 0"])
      s.add_runtime_dependency(%q<emitter>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<sniff>, [">= 0"])
      s.add_dependency(%q<emitter>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<sniff>, [">= 0"])
    s.add_dependency(%q<emitter>, [">= 0"])
  end
end

